pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building project...'
                dir('sample-app') {
                    bat 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('sample-app') {
                    bat 'mvn test'
                }
            }
        }
    }
}
